# 2019-03-11: Use Xenial distribution
# For Python v3.7 support, but drops v2.6 at the other end.

# Gets the useful versions, at least. v3.4 is a good oldest 3.x version
# to support; that's where the windows binaries for Gtk Introspection are.

# Will watch for better support with the default diistribution; even so,
# v3.0 - v3.3 will likely continue to be unsupported, but maybe those 
# can be tested locally.

dist: xenial

# codecov.io support

# Disable sudo to speed up the build
# codecov.io suggestion, is travis really using sudo? with python?
sudo: false

# Install the codecov pip dependency
install:
  - pip install codecov

language: python

python:
#  - "2.6"
  - "2.7"
#  - "3.4"
#  - "3.5"
#  - "3.6"
#  - "3.7"

script:
  - pytest

# Push the results back to codecov
after_success:
  - codecov
